apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: sample-blog
  description: デモンストレーション用のサービスです
  labels:
    app: sample-blog
  annotations:
    backstage.io/kubernetes-labal-selector: 'app=sample-blog'
    backstage.io/kubernetes-namespace: sample-blog
spec:
  type: website
  owner: user:default/bkuser1
  lifecycle: production
