apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: sample-blog
  description: |
    デモンストレーション用のサービスです。
    [利用方法]
    Catalog - Self-service - Import an existing Git repository をクリックし、
    URL に https://github.com/hiroyha-r/sample-catalog/blob/main/catalog-info.yaml を入力。
  labels:
    app: sample-blog
  annotations:
    backstage.io/kubernetes-label-selector: 'app=sample-blog'
    backstage.io/kubernetes-namespace: sample-blog
spec:
  type: website
  owner: user:default/bkuser1
  lifecycle: production
