apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: template1
  namespace: templates
  title: Template1
  description: Template 1
spec:
  owner: user:default/hiroyha-r
  type: service

  parameters:
    - title: input1
      required:
        - ownEntity
      properties:
        ownEntity:
          title: target
          type: string
          "ui:field": OwnedEntityPicker
          "ui:options":
            catalogFilter:
            - kind: component
              metadata.namespace: internal-systems
  steps:
    - id: fetch
      name: fetch entity
      action: catalog:fetch
      input:
        entityRef: ${{ parameters.ownEntity }}
    - id: debug
      name: debug
      action: debug:log
      input:
        message: ${{ steps.fetch.output.entity.metadata.name }}

  output:
    text:
      - title: Information
        content: |
          ${{ steps.fetch.output.entity.metadata.name }}
